#!/usr/bin/env python
"""Generate the synthetic participant bundled with this repository.

Everything under data/synthetic_001/ is produced by this script. No real
participant data is used anywhere in this repository, and none is required to
run the agent.

The generator is deliberately simple and readable rather than physiologically
faithful. It is here so that a reader can see exactly how the demo data was
fabricated, and can regenerate or vary it:

    python data/make_synthetic_data.py                  # rewrite data/synthetic_001/
    python data/make_synthetic_data.py --days 21 --seed 7

What it produces:

  cgm.csv       14 days at 15-minute cadence. A circadian baseline with a dawn
                rise, plus a post-prandial excursion after each logged meal
                scaled by that meal's carbohydrate content, plus sensor noise.
                With the default seed this lands at mean ~117 mg/dL,
                time-in-range ~94%, CV ~31% - broadly normal control with
                pronounced post-prandial excursions, so the report has
                something to say without being alarming.

  diet.csv      3 meals a day drawn from a small generic food table, with
                timings jittered. A few rows are deliberately corrupted so the
                diet_qc tool has something real to report - see SEEDED_FAULTS.

  metadata.json Participant demographics.

Note on the seeded faults: if the diet log is clean, qc_diet_data reports
"all pass" and contributes nothing to the demo report. The faults exercise the
completeness, range and consistency rule groups so the generated report has a
genuine data-quality section.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import numpy as np
import pandas as pd

# --- Participant -----------------------------------------------------------

PARTICIPANT_ID = "synthetic_001"

METADATA = {
    "participant_id": PARTICIPANT_ID,
    "age": 54,
    "sex": "female",
    "bmi": 27.4,
    "note": "Synthetic participant. Not a real person. Generated by make_synthetic_data.py.",
}

# --- CGM model -------------------------------------------------------------

CADENCE_MINUTES = 15
BASELINE_MGDL = 92.0          # overnight fasting level
DAWN_RISE_MGDL = 12.0         # dawn phenomenon amplitude
SENSOR_NOISE_SD = 4.0         # within-sensor measurement noise
DAY_TO_DAY_SD = 6.0           # slow drift between days

# Post-prandial response: amplitude per gram of carbohydrate, and the shape of
# the excursion (time to peak and decay), in minutes.
MGDL_PER_G_CARB = 1.25
PEAK_MINUTES = 45.0
DECAY_MINUTES = 75.0

# Identical meals do not produce identical responses, within or between people.
# This lognormal gain per meal is what stops every excursion looking the same,
# and is the main driver of the coefficient of variation.
MEAL_GAIN_LOG_SD = 0.32

# --- Food table ------------------------------------------------------------
# Generic foods with round, textbook-ish nutrient values. Not drawn from any
# food composition database.
# (name, category, weight_g, kcal, carb_g, protein_g, lipid_g, fibre_g, sodium_mg)
BREAKFAST_FOODS = [
    ("Porridge with milk", "Cereals and grains", 250, 220, 34.0, 8.0, 5.0, 4.0, 120),
    ("Wholemeal toast", "Bread", 60, 150, 26.0, 6.0, 2.0, 4.0, 300),
    ("Scrambled eggs", "Eggs", 120, 180, 2.0, 13.0, 13.0, 0.0, 350),
    ("Banana", "Fruit", 120, 105, 27.0, 1.3, 0.4, 3.1, 1),
    # Nutrient values must be self-consistent under the Atwater factors
    # (4/4/9 kcal per g of carb/protein/fat), or the diet_qc consistency rule
    # fires on every row and drowns out the deliberately seeded faults.
    ("Black coffee", "Drinks", 240, 2, 0.0, 0.5, 0.0, 0.0, 5),
]
LUNCH_FOODS = [
    ("Chicken breast, grilled", "Poultry", 150, 250, 0.0, 46.0, 5.0, 0.0, 110),
    ("White rice, cooked", "Cereals and grains", 200, 260, 56.0, 5.0, 0.6, 0.8, 2),
    ("Mixed salad", "Vegetables", 150, 45, 6.0, 2.0, 1.0, 3.0, 30),
    ("Lentil soup", "Pulses", 300, 230, 36.0, 15.0, 2.0, 12.0, 700),
    ("Wholemeal pasta", "Cereals and grains", 220, 300, 60.0, 11.0, 2.0, 8.0, 5),
]
DINNER_FOODS = [
    ("Baked salmon", "Fish", 160, 320, 0.0, 36.0, 19.0, 0.0, 90),
    ("Roast potatoes", "Vegetables", 200, 290, 44.0, 5.0, 10.0, 5.0, 250),
    ("Steamed broccoli", "Vegetables", 120, 40, 7.0, 3.0, 0.4, 3.0, 35),
    ("Beef stir fry", "Meat", 200, 380, 12.0, 32.0, 22.0, 3.0, 800),
    ("Greek yoghurt", "Dairy", 170, 100, 6.0, 17.0, 0.7, 0.0, 60),
    ("Dark chocolate", "Sweets", 30, 170, 13.0, 2.0, 12.0, 3.0, 6),
]

MEAL_SLOTS = [
    ("breakfast", 8.0, BREAKFAST_FOODS, 3),
    ("lunch", 13.0, LUNCH_FOODS, 3),
    ("dinner", 19.5, DINNER_FOODS, 3),
]

# Rows deliberately corrupted so the QC tool has findings to report.
# (day_index, meal_slot, fault) - see the module docstring.
SEEDED_FAULTS = [
    (3, "lunch", "missing_macro"),       # completeness: core macro is NA
    (6, "dinner", "implausible_weight"),  # range: weight_g >= 2000
    (9, "breakfast", "macro_mismatch"),   # consistency: kcal disagrees with macros
]


def _meal_response(minutes_since_meal: np.ndarray, carbs_g: float) -> np.ndarray:
    """Glucose excursion following a meal, in mg/dL.

    A difference-of-exponentials shape: rises to a peak around PEAK_MINUTES and
    decays back to baseline over a few hours. Amplitude scales with the meal's
    carbohydrate content.
    """
    t = np.clip(minutes_since_meal, 0.0, None)
    shape = np.exp(-t / DECAY_MINUTES) - np.exp(-t / (PEAK_MINUTES / 2.5))
    shape = np.clip(shape, 0.0, None)
    if shape.max() > 0:
        shape = shape / shape.max()
    shape[minutes_since_meal < 0] = 0.0
    return MGDL_PER_G_CARB * carbs_g * shape


def generate_meals(rng: np.random.Generator, start: datetime, days: int) -> pd.DataFrame:
    """Build the diet log, including the deliberately faulty rows."""
    rows = []
    food_id = 0

    for day in range(days):
        day_start = start + timedelta(days=day)

        for slot_name, slot_hour, food_pool, n_items in MEAL_SLOTS:
            # Jitter the meal time by up to ~40 minutes either side
            hour = slot_hour + rng.normal(0.0, 0.45)
            meal_time = day_start + timedelta(hours=float(hour))

            chosen = rng.choice(len(food_pool), size=n_items, replace=False)
            fault = next(
                (f for (d, s, f) in SEEDED_FAULTS if d == day and s == slot_name), None
            )

            for i, idx in enumerate(chosen):
                name, category, weight, kcal, carb, protein, lipid, fibre, sodium = food_pool[idx]

                # Vary portion size a little, and scale nutrients with it
                scale = float(rng.normal(1.0, 0.12))
                scale = float(np.clip(scale, 0.7, 1.4))
                weight_g = round(weight * scale, 1)
                calories = round(kcal * scale, 1)
                carbohydrate_g = round(carb * scale, 1)
                protein_g = round(protein * scale, 1)
                lipid_g = round(lipid * scale, 1)
                fibre_g = round(fibre * scale, 1)
                sodium_mg = round(sodium * scale, 1)

                # Apply the seeded fault to the first item of the target meal
                if fault and i == 0:
                    if fault == "missing_macro":
                        carbohydrate_g = np.nan
                    elif fault == "implausible_weight":
                        weight_g = 2400.0
                    elif fault == "macro_mismatch":
                        # Atwater sum will disagree with the reported calories
                        calories = round(calories * 2.2, 1)

                food_id += 1
                rows.append({
                    "food_id": f"F{food_id:05d}",
                    "collection_timestamp": meal_time,
                    "local_timestamp": meal_time,
                    "collection_date": meal_time.date().isoformat(),
                    "short_food_name": name,
                    "product_name": name,
                    "food_category": category,
                    "weight_g": weight_g,
                    "calories_kcal": calories,
                    "carbohydrate_g": carbohydrate_g,
                    "protein_g": protein_g,
                    "lipid_g": lipid_g,
                    "dietary_fiber_g": fibre_g,
                    "sodium_mg": sodium_mg,
                    "alcohol_g": 0.0,
                })

    return pd.DataFrame(rows)


def generate_cgm(rng: np.random.Generator, meals: pd.DataFrame,
                 start: datetime, days: int) -> pd.DataFrame:
    """Build the CGM trace, driven by the meals in `meals`."""
    n_points = days * 24 * 60 // CADENCE_MINUTES
    timestamps = [start + timedelta(minutes=CADENCE_MINUTES * i) for i in range(n_points)]
    ts = pd.Series(timestamps)

    hours = ts.dt.hour + ts.dt.minute / 60.0

    # Circadian baseline: a dawn rise peaking around 06:00, plus a slow
    # day-to-day drift so the days are not identical.
    dawn = DAWN_RISE_MGDL * np.exp(-((hours - 6.0) ** 2) / 8.0)
    day_index = (ts - ts.iloc[0]).dt.days.to_numpy()
    drift = rng.normal(0.0, DAY_TO_DAY_SD, size=days)[day_index]

    glucose = BASELINE_MGDL + dawn.to_numpy() + drift

    # Add one excursion per meal, keyed on that meal's carbohydrate content.
    minutes = (ts - ts.iloc[0]).dt.total_seconds().to_numpy() / 60.0
    meal_carbs = (
        meals.groupby("collection_timestamp")["carbohydrate_g"].sum(min_count=1).fillna(0.0)
    )
    for meal_time, carbs in meal_carbs.items():
        offset = (meal_time - ts.iloc[0]).total_seconds() / 60.0
        gain = float(rng.lognormal(0.0, MEAL_GAIN_LOG_SD))
        glucose = glucose + gain * _meal_response(minutes - offset, float(carbs))

    glucose = glucose + rng.normal(0.0, SENSOR_NOISE_SD, size=n_points)
    glucose = np.clip(glucose, 40.0, 400.0)

    return pd.DataFrame({
        "collection_timestamp": ts,
        "glucose": np.round(glucose, 1),
    })


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--days", type=int, default=14, help="Days of data to generate")
    parser.add_argument("--seed", type=int, default=20240101, help="Random seed")
    parser.add_argument(
        "--out", type=Path, default=Path(__file__).parent / PARTICIPANT_ID,
        help="Output directory",
    )
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)
    # A fixed, obviously-synthetic start date in UTC
    start = datetime(2024, 1, 1, 0, 0, tzinfo=timezone.utc)

    meals = generate_meals(rng, start, args.days)
    cgm = generate_cgm(rng, meals, start, args.days)

    args.out.mkdir(parents=True, exist_ok=True)
    cgm.to_csv(args.out / "cgm.csv", index=False)
    meals.to_csv(args.out / "diet.csv", index=False)
    (args.out / "metadata.json").write_text(json.dumps(METADATA, indent=2) + "\n")

    in_range = ((cgm["glucose"] >= 70) & (cgm["glucose"] <= 180)).mean() * 100
    print(f"Wrote {args.out}")
    print(f"  cgm.csv   {len(cgm)} rows over {args.days} days")
    print(f"            mean {cgm['glucose'].mean():.1f} mg/dL, "
          f"CV {cgm['glucose'].std() / cgm['glucose'].mean() * 100:.1f}%, "
          f"TIR {in_range:.1f}%")
    print(f"  diet.csv  {len(meals)} rows, {len(SEEDED_FAULTS)} seeded QC faults")
    print(f"  metadata.json")
    print("\nGround truth is generated separately by run_report.py --write-ground-truth")


if __name__ == "__main__":
    main()
